m = float(input('Uma distância em metros: '))
print(f'A medida de {m:.1f} corresponde a')
print(f'{m / 1000}km')
print(f'{m / 100}hm')
print(f'{m / 10}dam')
print(f'{m * 10:.0f}dm')
print(f'{m * 100:.0f}cm')
print(f'{m * 1000:.0f}mm')
